Repository Neovici/cosmoz-omnitable, pull requests merged in 2019-03, with the labels that each got.

#256 (patch #255) Should use arrow function and avoid binding "this".
  cosmoz-omnitable-group-row.html
Labels: enhancement

#258 Upgrade <cosmoz-omnitable> to Polymer 2.x
  cosmoz-omnitable-column-list-data.html
  cosmoz-omnitable-item-expand.html
  cosmoz-omnitable-repeater-mixin.html
  cosmoz-omnitable-templatizer.html
  cosmoz-omnitable.html
  cosmoz-omnitable.js
  test/basic.html
  test/group.html
  test/hash-param.html
  test/helpers/utils.js
  test/range-date.html
  test/range.html
  test/xlsx-export.html
Labels: 2.x, enhancement

#264 (patch) Update Polymer 2.x imports
  cosmoz-omnitable-column-amount.html
  cosmoz-omnitable-column-autocomplete.html
  cosmoz-omnitable-column-boolean.html
  cosmoz-omnitable-column-date-mixin.html
  cosmoz-omnitable-column-date.html
  cosmoz-omnitable-column-datetime.html
  cosmoz-omnitable-column-list-data.html
  cosmoz-omnitable-column-list-horizontal.html
  cosmoz-omnitable-column-list-mixin.html
  cosmoz-omnitable-column-list.html
  cosmoz-omnitable-column-mixin.html
  cosmoz-omnitable-column-number.html
  cosmoz-omnitable-column-range-mixin.html
  cosmoz-omnitable-column-time.html
  cosmoz-omnitable-column.html
  cosmoz-omnitable-group-row.html
  cosmoz-omnitable-header-row.html
  cosmoz-omnitable-item-expand-line.html
  cosmoz-omnitable-item-expand.html
  cosmoz-omnitable-item-row.html
  cosmoz-omnitable-item.html
  cosmoz-omnitable-repeater-mixin.html
  cosmoz-omnitable-styles.html
  cosmoz-omnitable-templatizer.html
  cosmoz-omnitable.html
Labels: 2.x, enhancement

#268 Adding Sauce Labs configuration
  .travis.yml
Labels: enhancement

#269 Rework templatizing
  analysis.json
  cosmoz-omnitable-column-mixin.html
  cosmoz-omnitable-group-row.html
  cosmoz-omnitable-header-row.html
  cosmoz-omnitable-item-expand.html
  cosmoz-omnitable-item-row.html
  cosmoz-omnitable-repeater-mixin.html
  cosmoz-omnitable-templatize-mixin.html
  cosmoz-omnitable-templatizer.html
  cosmoz-omnitable.js
  demo/detach_test.html
  demo/full-demo.html
  demo/helpers/hash-param-template.html
  demo/helpers/x-page.html
  demo/templatizer-test.html
  test/.eslintrc.json
  test/basic.html
  test/helpers/fixtures/basic-column.html
  test/helpers/fixtures/basic-row.html
  test/index.html
  test/integration/templatize.html
  test/repeater.html
  test/templatize-mixin.html
Labels: 2.x, enhancement

#271 Check if label should float based on validity
  cosmoz-omnitable-column-number.html
  test/range.html
Labels: bug

#273 (minor) expose Cosmoz.DateColumnMixin.toLocalISOString
  cosmoz-omnitable-column-date-mixin.html
Labels: bug
