Repository Neovici/cosmoz-omnitable, pull requests merged in 2019-10, with the labels that each got.

#309 fix for bug with list column norefs
  cosmoz-omnitable-column-mixin.js
Labels: bug

#311 fix(filter): free text filters don't persist
  cosmoz-omnitable-column.js
  test/hash-param.html
Labels: bug, high priority

#312 Transition to semantic release
  .github/workflows/workflow.yml
  .travis.yml
  README.md
  cosmoz-omnitable-column.js
  package-lock.json
  package.json
Labels: enhancement

#314 fix(styling): make hidden attribute apply display: none
  .jslintrc
  cosmoz-omnitable-styles.js
  package-lock.json
Labels: bug

#323 Cleanup private interface
  cosmoz-omnitable.js
  test/xlsx-export.html
Labels: enhancement

#329 fix: `all selected` checkbox is checked
  cosmoz-omnitable.js
  test/xlsx-export.html
  wct.conf.json
Labels: bug

#327 chore(ci): fix codeclimate coverage reporting
  .github/workflows/workflow.yml
  wct.conf.json
Labels: enhancement

#330 fix: make sure spinner in autocomplete is properly hidden
  cosmoz-omnitable-column-autocomplete.js
Labels: bug
