Repository Neovici/cosmoz-omnitable, pull requests merged in 2019-05, with the labels that each got.

#279 saving csv created faulty content with horizontal list columns
  cosmoz-omnitable-column-list-horizontal.html
  cosmoz-omnitable-column-list-mixin.html
Labels: bug

#280 Fixed extend order and moved toXlsvValue to Mixin both extends from
  cosmoz-omnitable-column-list-horizontal.html
  cosmoz-omnitable-column-list-mixin.html
  cosmoz-omnitable-column-list.html
Labels: bug, enhancement

#281 Demo, Test, replacing demo behavior with helper
  demo/ajax-demo.html
  demo/custom-template-demo.html
  demo/detach_test.html
  demo/editable-demo.html
  demo/empty-demo.html
  demo/filter-demo.html
  demo/group-on-demo.html
  demo/helpers/x-page.html
  demo/multi-filter-demo.html
  demo/sort-demo.html
  demo/styling.html
  demo/table-demo-behavior.html
  demo/table-demo-helper.html
  test/basic.html
  test/boolean.html
  test/group.html
  test/list.html
  test/range-date.html
  test/range.html
  test/xlsx-export.html
Labels: 2.x, enhancement

#282 Component, replacing translation behavior with mixin, upgrading cosmoz-i18next component
  bower.json
  cosmoz-omnitable-column-amount.html
  cosmoz-omnitable-column-date.html
  cosmoz-omnitable-column-datetime.html
  cosmoz-omnitable-column-list-data.html
  cosmoz-omnitable-column-list-horizontal.html
  cosmoz-omnitable-column-list.html
  cosmoz-omnitable-column-number.html
  cosmoz-omnitable-column-time.html
  cosmoz-omnitable.js
Labels: enhancement

#283 Demo, converting views to class-style
  cosmoz-omnitable-column-list-data.html
  cosmoz-omnitable.js
  demo/editable-demo.html
  demo/filter-demo.html
  demo/multi-filter-column.html
  demo/multi-filter-demo.html
  demo/styling.html
Labels: 2.x, enhancement

#284 Demo, converting views to class-style
  demo/custom-template-demo.html
  demo/detach_test.html
  demo/empty-demo.html
  demo/group-on-demo.html
  demo/sort-demo.html
Labels: 2.x, enhancement

#285 Demo, Test, converting views to class-style
  demo/ajax-demo.html
  demo/detach_test.html
  demo/editable-demo.html
  demo/empty-demo.html
  demo/filter-demo.html
  demo/group-on-demo.html
  demo/helpers/cosmoz-translations.html
  demo/helpers/x-page.html
  demo/index.html
  demo/multi-filter-demo.html
  demo/sort-demo.html
  demo/styling.html
  test/group.html
  test/integration/templatize.html
Labels: 2.x, enhancement

#286 Components, UI-helpers, adding mixin definitions, converting UI-helpers to class-style
  cosmoz-omnitable-column-amount.html
  cosmoz-omnitable-column-date.html
  cosmoz-omnitable-column-datetime.html
  cosmoz-omnitable-column-list-data.html
  cosmoz-omnitable-column-list-horizontal.html
  cosmoz-omnitable-column-list.html
  cosmoz-omnitable-column-number.html
  cosmoz-omnitable-column-time.html
  cosmoz-omnitable.js
  ui-helpers/cosmoz-clear-button.html
Labels: 2.x, enhancement

#287 Components, Demo, converting to class-style
  analysis.json
  bower.json
  cosmoz-omnitable-column-list-data.html
  cosmoz-omnitable.js
  demo/helpers/x-page.html
Labels: 2.x, enhancement

#288 (dev) polymer lint fails because of missing annotations
  analysis.json
  cosmoz-omnitable-column-list-data.html
  cosmoz-omnitable.js
Labels: bug
