Repository Neovici/cosmoz-omnitable, pull requests merged in 2020-10, with the labels that each got.

#390 Feature/389 remove iron flex layout
  cosmoz-omnitable-column-boolean.js
  cosmoz-omnitable-column-list-data.js
  cosmoz-omnitable-column-number.js
  cosmoz-omnitable-group-row.js
  cosmoz-omnitable-header-row.js
  cosmoz-omnitable-item-expand-line.js
  cosmoz-omnitable-item-expand.js
  cosmoz-omnitable-item-row.js
  cosmoz-omnitable-item.js
  cosmoz-omnitable-styles.js
  cosmoz-omnitable.js
  demo/ajax-demo.html
  demo/custom-template-demo.html
  demo/detach_test.html
  demo/editable-demo.html
  demo/empty-demo.html
  demo/filter-demo.html
  demo/full-demo.html
  demo/group-on-demo.html
  demo/hash-param.html
  demo/helpers/hash-param-template.html
  demo/helpers/x-page.js
  demo/index.html
  demo/multi-filter-column.js
  demo/multi-filter-demo.html
  demo/sort-demo.html
  demo/styling.html
  package-lock.json
  package.json
  test/basic.test.js
  test/boolean.test.js
  test/group.test.js
  test/integration/column-number.test.js
  test/integration/templatize.test.js
  test/list.test.js
  test/range-date.test.js
  test/range.test.js
  test/xlsx-export.test.js
Labels: enhancement

#391 fix(render): grouped list renders old items
  cosmoz-omnitable.js
Labels: bug, high priority

#393 fix: always selectable if data is valid
  cosmoz-omnitable.js
  shell.nix
Labels: bug, enhancement

#394 fix: handles null values in list columns
  cosmoz-omnitable-column-list-mixin.js
Labels: bug

#395 fix: upgrade to latest bottom-bar
  cosmoz-omnitable.js
  package-lock.json
  package.json
Labels: bug, high priority
