Repository Neovici/cosmoz-omnitable, pull requests merged in 2021-09, with the labels that each got.

#450 Settings ui
  cosmoz-omnitable-header-row.js
  cosmoz-omnitable-item-row.js
  cosmoz-omnitable-styles.js
  cosmoz-omnitable.js
  get-effective-children-legacy-mixin.js
  lib/cosmoz-omnitable-settings.js
  lib/use-omnitable.js
  package-lock.json
  package.json
  test/helpers/utils.js
Labels: enhancement

#456 fix(settings): toggle settings Toggle settings by clicking the button
  lib/cosmoz-omnitable-settings.js
  package-lock.json
  package.json
Labels: bug, enhancement

#457 fix: playwright can't locate elements via the for attribute
  cosmoz-omnitable-header-row.js
  cosmoz-omnitable-item-row.js
  lib/compute-layout.js
Labels: bug

#459 fix(layout): error when columns are hidden conditionally
  lib/compute-layout.js
Labels: bug, high priority
