Repository Neovici/cosmoz-omnitable, pull requests merged in 2021-03, with the labels that each got.

#420 Feature/wtr
  .github/workflows/workflow.yml
  README.md
  cosmoz-omnitable-column-amount.js
  cosmoz-omnitable-column-autocomplete.js
  cosmoz-omnitable-column-boolean.js
  cosmoz-omnitable-column-date-mixin.js
  cosmoz-omnitable-column-date.js
  cosmoz-omnitable-column-datetime.js
  cosmoz-omnitable-column-list-horizontal.js
  cosmoz-omnitable-column-list-mixin.js
  cosmoz-omnitable-column-list.js
  cosmoz-omnitable-column-mixin.js
  cosmoz-omnitable-column-range-mixin.js
  cosmoz-omnitable-column-time.js
  cosmoz-omnitable-column.js
  cosmoz-omnitable-header-row.js
  cosmoz-omnitable-item-expand.js
  cosmoz-omnitable-item.js
  cosmoz-omnitable-repeater-mixin.js
  cosmoz-omnitable.js
  es-dev-server.config.js
  karma.conf.js
  package-lock.json
  package.json
  shell.nix
  test/basic.test.js
  test/integration/column-number.test.js
  test/range.test.js
  web-dev-server.config.mjs
  web-test-runner.config.mjs
Labels: dependencies, enhancement

#421 feat(cosmoz-omnitable): renders totalAvailable in row stats
  cosmoz-omnitable.js
  test/basic.test.js
Labels: enhancement

#419 Migrate default templates to render functions
  cosmoz-omnitable-column-amount.js
  cosmoz-omnitable-column-autocomplete.js
  cosmoz-omnitable-column-boolean.js
  cosmoz-omnitable-column-date.js
  cosmoz-omnitable-column-datetime.js
  cosmoz-omnitable-column-list-horizontal.js
  cosmoz-omnitable-column-list-mixin.js
  cosmoz-omnitable-column-list.js
  cosmoz-omnitable-column-mixin.js
  cosmoz-omnitable-column-number.js
  cosmoz-omnitable-column-range-mixin.js
  cosmoz-omnitable-column-time.js
  cosmoz-omnitable-column.js
  cosmoz-omnitable-group-row.js
  cosmoz-omnitable-header-row.js
  cosmoz-omnitable-item-expand.js
  cosmoz-omnitable-item-row.js
  cosmoz-omnitable-repeater-mixin.js
  cosmoz-omnitable-templatize-mixin.js
  demo/ajax-demo.html
  demo/custom-template-demo.html
  demo/detach_test.html
  demo/editable-demo.html
  demo/empty-demo.html
  demo/filter-demo.html
  demo/full-demo.html
  demo/group-on-demo.html
  demo/hash-param.html
  demo/helpers/x-page.js
  demo/multi-filter-demo.html
  demo/sort-demo.html
  demo/styling.html
  docs/documentation.md
  test/autocomplete.test.js
  test/basic.test.js
  test/group.test.js
  test/hash-param.test.js
  test/helpers/fixtures/basic-column.js
  test/helpers/fixtures/basic-row.js
  test/integration/templatize.test.js
  test/list.test.js
  test/range-date.test.js
  test/repeater.html
  test/repeater.test.js
  test/templatize-mixin.html
Labels: enhancement

#422 fix: expanded rows don't update size after column changes
  cosmoz-omnitable-item-expand.js
Labels: bug

#423 fix: migrate header-row to haunted
  cosmoz-omnitable-header-row.js
  cosmoz-omnitable.js
  lib/use-force-render.js
  lib/use-render-on-column-updates.js
  package.json
  test/basic.test.js
  test/integration/column-number.test.js
  test/range.test.js
Labels: enhancement
