Repository Neovici/cosmoz-omnitable, pull requests merged in 2022-01, with the labels that each got.

#486 fix: use null for filter reset
  cosmoz-omnitable-column.js
Labels: bug

#487 fix(default-column): workaround for double-encoded filters
  cosmoz-omnitable-column-mixin.js
  lib/use-hash-state.js
  lib/use-processed-items.js
  test/basic.test.js
Labels: enhancement

#489 fix(legacy): column.filter to internal state mapping
  cosmoz-omnitable-column-mixin.js
  cosmoz-omnitable-column.js
  lib/use-omnitable.js
  lib/use-processed-items.js
Labels: bug, high priority
