Repository Neovici/cosmoz-omnitable, pull requests merged in 2022-06, with the labels that each got.

#526 fix: iron-list bug
  package-lock.json
  package.json
Labels: bug

#528 feat(sort-and-group): implement correct reset
  lib/settings/normalize.js
  lib/settings/use-saved-settings.js
  lib/settings/use-settings.js
  lib/use-omnitable.js
  lib/use-sort-and-group-options.js
Labels: bug, enhancement

#531 feat: upgrade to lit@^2
  cosmoz-omnitable-header-row.js
  cosmoz-omnitable-item-row.js
  demo/hash-param.html
  lib/cosmoz-omnitable-amount-range-input.js
  lib/cosmoz-omnitable-date-range-input.js
  lib/cosmoz-omnitable-datetime-range-input.js
  lib/cosmoz-omnitable-number-range-input.js
  lib/cosmoz-omnitable-time-range-input.js
  lib/settings/cosmoz-omnitable-group.js
  lib/use-hash-state.js
  package-lock.json
  package.json
  test/basic.test.js
  test/range-amount.test.js
  test/range-date.test.js
  test/range.test.js
  test/xlsx-export.test.js
Labels: enhancement, dependencies

#533 test: ctrl click to remain one item selected
  test/select.test.js
Labels: unit

#535 test: deselect all items from all checkbox
  test/select.test.js
Labels: unit
