Repository Neovici/cosmoz-omnitable, pull requests merged in 2022-10, with the labels that each got.

#542 fix(use-settings): error when removing columns
  lib/settings/use-settings.js
Labels: bug

#546 fix: sortOn and descending changes are not notified
  lib/use-public-interface.js
Labels: bug

#548 fix: selected-items-changed is sent too late
  cosmoz-omnitable.js
  test/hash-param-read.test.js
Labels: bug, high priority

#549 feat(number-column): use same width for number chars
  cosmoz-omnitable-styles.js
  lib/settings/style.css.js
Labels: enhancement
