Repository Neovici/cosmoz-omnitable, pull requests merged in 2022-03, with the labels that each got.

#496 fix(deps): update cosmoz-page-router
  package-lock.json
  package.json
Labels: enhancement

#497 fix(use-dom-columns): changes to enabled columns are ignored
  lib/use-dom-columns.js
Labels: bug, high priority

#498 feat(deps): upgrade cosmoz-bottom-bar
  cosmoz-omnitable-styles.js
  package-lock.json
  package.json
Labels: enhancement, dependencies

#499 Unit/new tests
  .editorconfig
  .eslintrc.json
  .github/workflows/workflow.yml
  .prettierrc
  lib/utils-amount.js
  package-lock.json
  package.json
  test/utils-amount.test.js
  web-test-runner.config.mjs
Labels: unit

#500 feat(cosmoz-autocomplete): upgrade
  package-lock.json
  package.json
Labels: enhancement, dependencies
