Repository Neovici/cosmoz-omnitable, pull requests merged in 2025-04, with the labels that each got.

#646 fix(vars): graphical elements of omnitable need external control for …
  cosmoz-omnitable-styles.js
Labels: enhancement, released, css vars

#647 Fix/ab19255 omnitable theme vars
  cosmoz-omnitable-styles.js
Labels: css vars

#650 fix: remove whitespaces in header
  cosmoz-omnitable-header-row.js
Labels: enhancement
